FROM node:20-alpine

# Carpeta de trabajo dentro del contenedor
WORKDIR /usr/src/app

# Copiamos solo los archivos de dependencias primero (mejor cache)
COPY package*.json ./

# Instalamos dependencias (solo prod si quieres)
RUN npm install --only=production

# Copiamos el resto del código
COPY . .

# Variable de entorno por defecto
ENV NODE_ENV=production

# Puerto que expone la app
EXPOSE 3000

# Comando por defecto (usa app.js -> "start": "node app.js")
CMD ["npm", "start"]
